# Generated by Django 5.2.1 on 2025-05-09 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantTrackingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('ats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiMatch.applicanttrackingsystem')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStageMapping',
            fields=[
                ('ats_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aiMatch.applicationstage')),
                ('explanation', models.CharField(max_length=500)),
            ],
        ),
    ]
