# Generated by Django 5.2.1 on 2025-05-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiMatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstagemapping',
            name='hireport_stage',
            field=models.CharField(choices=[('JR', 'Job Requisition and Approval'), ('JP', 'Job Posting'), ('AC', 'Application Collection'), ('SN', 'Screening'), ('IP', 'Interview Process'), ('FE', 'Feedback and Evaluation'), ('OM', 'Offer Management'), ('HO', 'Hiring and Onboarding')], default='JR', max_length=2),
        ),
    ]
