# Generated by Django 5.2.1 on 2025-05-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiMatch', '0002_applicationstagemapping_hireport_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstage',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
